# Generated by Django 5.1.3 on 2024-11-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='rbac.role'),
        ),
    ]
